"""Evidence aggregation utilities for the future verification workflow."""

from collections.abc import Mapping, Sequence
from typing import Any

from pydantic import BaseModel, Field

from app.services.search_service import SearchEvidence
from app.services.source_service import score_source


class EvidenceItem(BaseModel):
    source: str
    category: str
    credibility_score: int = Field(ge=0, le=100)
    title: str | None = None
    url: str | None = None
    snippet: str | None = None
    provider: str | None = None
    is_mock: bool = False


class EvidenceSummary(BaseModel):
    claim: str
    evidence_count: int
    average_credibility_score: float
    evidence: list[EvidenceItem]
    summary: str


def _as_mapping(source: SearchEvidence | Mapping[str, Any] | str) -> Mapping[str, Any]:
    if isinstance(source, SearchEvidence):
        return source.model_dump()
    if isinstance(source, str):
        return {"source": source}
    return source


class EvidenceService:
    """Prepare scored evidence summaries without deciding a claim's verdict."""

    async def summarize(
        self, claim: str, sources: Sequence[SearchEvidence | Mapping[str, Any] | str]
    ) -> EvidenceSummary:
        evidence: list[EvidenceItem] = []

        for source in sources:
            raw_source = _as_mapping(source)
            source_name = str(raw_source.get("source") or raw_source.get("domain") or "")
            credibility_subject = str(raw_source.get("domain") or source_name)
            credibility = score_source(credibility_subject)
            evidence.append(
                EvidenceItem(
                    source=source_name,
                    category=str(credibility["category"]),
                    credibility_score=int(credibility["credibility_score"]),
                    title=raw_source.get("title"),
                    url=raw_source.get("url"),
                    snippet=raw_source.get("snippet"),
                    provider=raw_source.get("provider"),
                    is_mock=bool(raw_source.get("is_mock", False)),
                )
            )

        average = (
            round(sum(item.credibility_score for item in evidence) / len(evidence), 1)
            if evidence
            else 0.0
        )
        summary = (
            f"Prepared {len(evidence)} evidence item(s) for claim review. "
            "No verdict has been generated by the evidence service."
        )

        return EvidenceSummary(
            claim=claim,
            evidence_count=len(evidence),
            average_credibility_score=average,
            evidence=evidence,
            summary=summary,
        )


async def prepare_evidence_summary(
    claim: str, sources: Sequence[SearchEvidence | Mapping[str, Any] | str]
) -> EvidenceSummary:
    """Convenience entry point for preparing a future verification evidence bundle."""
    return await EvidenceService().summarize(claim, sources)
